### PR TITLE
Stripe Checkout

### PR DESCRIPTION
**Pull request by andrewlew1s**
This PR adds:

- Stripe checkout cloud function that redirects user to stripe checkout payment flow and back to e-mailr success and cancel pages
- Success and cancel pages which link back to the home page

How to test:
- Choose to run local emulator and add stripe api key to cloud function to test locally or uncomment the prod call
- Enter some letter content
- Click the send mail button
- Fill out the payment details with the test card information:
- Enter 4242 4242 4242 4242 as the card number.
- Enter any future date for card expiry.
- Enter any 3-digit number for CVC.
- Enter any billing postal code.
- Click Pay.
- You’re redirected to the success page.
- (Click back arrow to go to cancel page.)

Todos:

- Decide what product data to pass to stripe
- Improve UI of success and cancel pages
- Decide how much to charge for mail (currently using random test amount of £20, could do based off letter length or other ideas)

Questions:

- Use axios or firebase docs method of calling firebase cloud functions
- How we want to load in dynamic variables e.g. localhost vs deployed api url && stripe keys
- Better route names

[Related issue](https://github.com/holistic-web/e-mailr/issues/7)

### CODE REVIEW

**Comment by fitzhavey** [comment]
Looks cool, and like there is some complexity to the payment flow. Let's walk through the PR together soon.

My initial question would be is it best to label our cloud function as a 'stripe-api' or perhaps our cloud function should handle both taking payment and sending the letter.

If we kept it focused to taking payments, maybe 'payments-api' is a better name?

**Comment by fitzhavey** [comment]
The Vue components look very nice 💥

**Comment by andrewlew1s** [comment]
Issue update:

- Success page will call second verifyPaymentAndSend function on load
- VerifyPaymentAndSend currently looks through all the documents associated with a user, we need a way to know which session / payment intent to check as users can have multiple

**Review by fitzhavey — APPROVED** [review]
lgtm

**Pull request merged**
